#!/bin/bash

for i in `find . -name __pycache__`; do rm -rf $i; done
for i in `find . -name .pyc`; do rm -rf $i; done
rm -f /tmp/shadowlands*.zip
VERSION=`cat ./VERSION`
echo "SL_VERSION='$VERSION'" | cat > shadowlands/version.py
zip -r /tmp/shadowlands-$VERSION.zip shadowlands/
