#!/bin/sh

if [ ! -d ~/.shadowlands ]; then
  for pythonfile in `which python3`; do
    if [ -f $pythonfile ]; then
      echo Found a usable python binary at `$pythonfile -V`
      break;
    fi
  done

  echo "Making a virtual python env for Shadowlands in ~/.shadowlands"
  mkdir -p ~/.shadowlands/cache
  touch ~/.shadowlands/firstrun
  $pythonfile -m venv ~/.shadowlands
fi

echo "Activating virtual python env for Shadowlands"
source ~/.shadowlands/bin/activate

cat << EOF > ~/.shadowlands/shadowlands.py
#!$HOME/.shadowlands/bin/python3
from subprocess import call
import sys, os, pdb, shutil
from pathlib import Path

first_run_tag = Path.home().joinpath(".shadowlands").joinpath("firstrun")
if first_run_tag.exists():
    # if it's MacOS and version 3.6, we'll fix ssl.

    print("Setting up SLoader dependencies...")
    # To stop pip from bitching constantly
    call(['pip', 'install', '--upgrade', 'pip'])

    for reqs in ["wget", "zipimport", "zipfile", "eth_utils", "web3"]:
        call(['pip', 'install', reqs])
    first_run_tag.unlink()

import zipimport
import zipfile
import hashlib
from time import sleep
import sys
import pdb
from eth_utils import encode_hex
import wget

SLOADER_MAINNET='0x99AF965b51312C8869FAc5f527F47Af92fCCf83C'
SLOADER_ABI='''[{"constant":true,"inputs":[],"name":"latestReleaseUrl","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"latestReleaseChecksum","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"}]'''

try:
    from web3.auto.infura import w3
    w3.isConnected() and w3.version.network == '1'
except:
    from web3.auto import w3
    if not (w3.isConnected() and w3.version.network == '1') :
        print("Could not get an eth node to bootstrap from, exiting.")
        sys.exit(1)

#pdb.set_trace()

print("")
print("Connected to " + w3.version.node)

print("Bootstrapping SLoader contract at " + SLOADER_MAINNET)
sloader_contract = w3.eth.contract(SLOADER_MAINNET, abi=SLOADER_ABI)

shadowlands_zip_url = sloader_contract.functions.latestReleaseUrl().call()
bytes32_checksum = sloader_contract.functions.latestReleaseChecksum().call()
shadowlands_checksum = encode_hex(bytes32_checksum).replace('0x','')
print("Contract reports latest checksum is " + shadowlands_checksum)

shadowlands_cache_dir = Path.home().joinpath(".shadowlands").joinpath("cache")

sl_zipfile = None

def filehasher(sl_zipfile):
    hasher = hashlib.sha256()
    with open(str(sl_zipfile), 'rb') as afile:
        buf = afile.read()
        hasher.update(buf)
        return hasher.hexdigest()

for cached_file in shadowlands_cache_dir.iterdir():
    if shadowlands_checksum == filehasher(cached_file):
        print("Checksum matched cached copy of Shadowlands...")
        sl_zipfile = cached_file
        break

if sl_zipfile is None:
    print("Getting latest Shadowlands version...")
    sl_zipfile = wget.download(shadowlands_zip_url, out=str(shadowlands_cache_dir))
    print(" ")
    if shadowlands_checksum != filehasher(str(sl_zipfile)):
        print("ERROR: Downloaded file did not pass checksum, aborting.")
        sys.exit(1)
    print("Checksum verified...")

    #cheating
    #sl_zipfile = Path.cwd().joinpath('shadowlands.zip')

    archive = zipfile.ZipFile(str(sl_zipfile), 'r')
    print("Gathering Shadowlands dependencies...")
    requirements = archive.read('shadowlands/requirements.txt')
    reqs = requirements.split()
    for req in reqs:
        print("Sloader pip installing {}".format(req) )
        call(['pip','install', req])
    archive.close()
    #sys.exit(0)

importer = zipimport.zipimporter(str(sl_zipfile))
print("Loading Shadowlands...")
mod = importer.load_module('shadowlands')

EOF

chmod 755 ~/.shadowlands/shadowlands.py
~/.shadowlands/shadowlands.py

