#!/bin/bash -l

while [[ $# -gt 0 ]]
do
  key="$1"


  case $key in
      --help)
      echo
      echo "Usage: shadowlands [arg]"
      echo
      echo "arguments:"
      echo "  --clean      Removes the installation at ~/.shadowlands."
      echo "  --help       This message"
      exit 
      ;;
      --clean)
      echo "Removing virtual python environment at ~/.shadowlands"
      rm -rf ~/.shadowlands
      exit
      ;;
      *)  
      echo "Unrecognized option; try 'shadowlands --help'"
      exit
      ;;
  esac
done

export PYTHONPATH=${PYTHONPATH}:..
SL_DIR=../shadowlands


case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX" ;;
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
*)        echo "unknown: $OSTYPE" ;;
esac

function make_shadowlands_dir {
  for pythonfile in `which python3.6` `which python3`; do
    if [ -f $pythonfile ]; then
      echo Found a usable python binary at `$pythonfile -V`
      break;
    fi
  done

  mkdir -p ~/.shadowlands/cache
  echo "Making a virtual python env for Shadowlands in ~/.shadowlands"
  $pythonfile -m venv ~/.shadowlands
  touch ~/.shadowlands/v1
  source ~/.shadowlands/bin/activate
  pip3 install -r $SL_DIR/requirements.txt --no-cache-dir || rm -rf ~/.shadowlands; echo "pip failed; rolling back venv install"
}

function activate_env {
  echo "Activating Shadowlands virtual environment"
  source ~/.shadowlands/bin/activate
}

if [ ! -d ~/.shadowlands ]; then
  make_shadowlands_dir
elif [ ! -f ~/.shadowlands/v1 ]; then
  rm -rf ~/.shadowlands
  make_shadowlands_dir
fi

activate_env
python3 -m shadowlands
#python3 /usr/local/lib/shadowlands-core/shadowlands.py

