#!/bin/bash -l

# Devs - Uncomment the following line 
# and point it to the cloned github repo
#SL_DIR=~/src/shadowlands


if [ -z "$SL_DIR" ]; then 
	case "$OSTYPE" in
	  #solaris*) echo "SOLARIS" ;;
	  darwin*)  echo "Detected $OSTYPE"; SL_DIR=/usr/local/opt/shadowlands/lib ;;
	  linux*)   echo "Running $OSTYPE"; SL_DIR=/usr/local/lib/shadowlands ;;
	  #bsd*)     echo "BSD" ;;
	*)        echo "unknown: $OSTYPE."; echo  Edit this script and see if you can make it better. ;;
	esac
fi

export PYTHONPATH=${PYTHONPATH}:$SL_DIR

#echo Shadowlands located at $SL_DIR

while [[ $# -gt 0 ]]
do
  key="$1"


  case $key in
      --help)
      echo
      echo "Usage: shadowlands [arg]"
      echo
      echo "arguments:"
      echo "  --clean      Removes the installation at ~/.shadowlands."
      echo "  --help       This message"
      exit 
      ;;
      --clean)
      echo "Removing virtual python environment at ~/.shadowlands"
      rm -rf ~/.shadowlands
      exit
      ;;
      *)  
      echo "Unrecognized option; try 'shadowlands --help'"
      exit
      ;;
  esac
done

function make_shadowlands_dir {
  for pythonfile in `which python3.6` `which python3`; do
    if [ -f $pythonfile ]; then
      echo Found a usable python binary at `$pythonfile -V`
      break;
    fi
  done

  mkdir -p ~/.shadowlands/cache
  echo "Making a virtual python env for Shadowlands in ~/.shadowlands"
  $pythonfile -m venv ~/.shadowlands
  touch ~/.shadowlands/v1
  source ~/.shadowlands/bin/activate
  pip3 install -r $SL_DIR/shadowlands/requirements.txt --no-cache-dir || rm -rf ~/.shadowlands; echo "pip failed; rolling back venv install"; exit 1
}

function activate_env {
  echo "Activating Shadowlands virtual environment"
  source ~/.shadowlands/bin/activate
}

if [ ! -d ~/.shadowlands ]; then
  make_shadowlands_dir
elif [ ! -f ~/.shadowlands/v1 ]; then
  rm -rf ~/.shadowlands
  make_shadowlands_dir
fi

activate_env
python3 -m shadowlands

